### ISSUE TITLE
Dynamic Chart - Uncaught TypeError: Cannot read property 'highlightFill' of undefined with empty series

### ISSUE THREAD

**Issue by PuKoren** [jtblin/angular-chart.js#31] opened 2015-01-15 11:23 UTC
When using a Dynamic Chart, *Bar* or *Radar*, and trying to change it to *Line*, this error occurs:

    Uncaught TypeError: Cannot read property 'highlightFill' of undefined

It happened only once, and I was not able to render the *Line* chart.

Now every time I reload the browser I have this error, on every type of chart. (But now they all render...)

Here are my options:
```js
$scope.options = {
		responsive: true,
		maintainAspectRatio: true,
		animation: false
};
```

I use a 3 series chart.

Note: with *animation* set to *true*, the error disappeared.

**Comment by jtblin** [comment] 2015-01-16 09:24
Could you please post a full jsbin or similar? I am not able to reproduce with a simple example.

```html
<div class="col-lg-6 col-sm-12" id="base-chart" ng-controller="BaseCtrl">
  <div class="panel panel-default">
    <div class="panel-heading">Dynamic Chart</div>
    <div class="panel-body">
      <canvas id="base" class="chart chart-base" chart-type="type" data="data" labels="labels" legend="true"></canvas>
    </div>
  </div>
  <button type="button" class="btn btn-primary pull-right" ng-click="toggle()">Toggle</button>
</div>
```

```javascript
  app.controller("BaseCtrl", function ($scope) {
    $scope.labels = ['2006', '2007', '2008', '2009', '2010', '2011', '2012'];
    $scope.series = ['Series A', 'Series B'];
    $scope.data = [
      [65, 59, 80, 81, 56, 55, 40],
      [28, 48, 40, 19, 86, 27, 90]
    ];
    $scope.type = 'Bar';

    $scope.toggle = function () {
      $scope.type = $scope.type === 'Bar' ?  'Line' : 'Bar';
    };
  });
```

Btw, it is not necessary to set `responsive` to `true`, this is the default value.

**Comment by jtblin** [comment] 2015-01-16 10:00
Here is a jsbin template for convenience: http://jsbin.com/dufibi/3/edit?html,js,output.

**Comment by PuKoren** [comment] 2015-01-16 16:57
I reproduced it here:
http://jsbin.com/wokumiqama/1/edit?html,js,output

When you mouse hover the bar, the errors is triggered

**Comment by jtblin** [comment] 2015-01-26 05:15
Thanks for the repro case, it doesn't seem to have any impact apart from the error in the console, and the issue is in Chart.js itself in:

				helpers.each(activeBars, function(activeBar){
					activeBar.fillColor = activeBar.highlightFill;
					activeBar.strokeColor = activeBar.highlightStroke;
				});

It doesn't check if `activeBar` exists.

**Comment by Nsab31** [comment] 2016-02-12 18:32
I got the same error. @PuKoren thanks for the solution @jtblin Thanks for the explanation. It saved my time :)

**Comment by Nsab31** [comment] 2016-02-12 19:41
When i hover over the chart, The legend doesn't show the colour of the series.Is this a bug ? or am I missing something ?

**Comment by jtblin** [comment] 2016-06-18 12:18
Given it's an issue with the deprecated version of chart.js, I'm going to close this issue now. Feel free to open a new one with Chart.js if this is still happening with the latest version.

**Closed by jtblin** 2016-06-18 12:18 UTC
Labels: bug, minor, upstream, v0.x
