### ISSUE TITLE
Chart disappear when changing tab on google chrome

### ISSUE THREAD

**Issue by CaptainYouz** [jtblin/angular-chart.js#346] opened 2016-03-23 10:49 UTC
Hi!

When I change tab on Google Chrome, sometimes the chart disappear, sometimes not.
(In my options, responsive is set to false)

**Comment by rmckeel** [comment] 2016-03-23 19:07
I have the same issue, so I can add some diagnostic information.

The issue appears when I change chart-data (through a background process updating information) for the chart-bar directive while on another tab, or minimized.  I am using a $timeout already to change chart-data.

There are several potential fixes I've reviewed, all of which seem hacky at the moment.  E.g., trigger a resize event:

`window.dispatchEvent(new Event('resize'));`

This works, but what if your app does something else on resize?  The window didn't actually resize..

I could also use the 'visibility API' with fallback to focus/blur events to detect when the user is looking again, but that's just a bandaid to the real underlying issue.

I am tracking related issues #29 and [Chart.js #961](https://github.com/nnnick/Chart.js/issues/961).

**Comment by rmckeel** [comment] 2016-03-23 19:16
PS I am testing against chart.js v1.0.2 Stable (latest stable tag) and angular-chart.js 0.9.0 (latest stable tag).

**Comment by rmckeel** [comment] 2016-03-24 13:07
I made a [JSBin](https://jsbin.com/nudibob/edit?html,js,output), unfortunately I was unable to reproduce the issue I am having..  Perhaps @CaptainYouz you can modify this jsbin to reproduce the issue on your computer?

**Comment by jtblin** [comment] 2016-06-18 12:11
I've added a `$resize` event that you can emit on the scope to force a resize as well. Gonna close this issue for now. Feel free to reopen if you have a repro step.

**Closed by jtblin** 2016-06-18 12:11 UTC
Labels: v0.x
