### ISSUE TITLE
Dynamic data update issue

### ISSUE THREAD

**Issue by ivanicharts** [jtblin/angular-chart.js#511] opened 2016-09-25 11:04 UTC
I have some troubles with updating data. So when i update my data, chart doesn't call update(), it calls destroy, so it seems that it redraw all the chart with new points, but not just add new points to current, without refreshing old. So how should i update my data in order to call update() fun ?

so i have smth like this:
http://jsbin.com/yaxubijoci/1/edit?html,js,output

and i need smth like this: 
https://jsfiddle.net/41bj1cpo/

Thanks.

**Comment by mathben** [comment] 2016-10-16 19:43
You example (first link) doesn't work, the initial data is not visible (error in console) on my browser (firefox 49)
http://jsbin.com/yaxubijoci/1/edit?html,js,output

**Comment by develmts** [comment] 2016-11-07 17:37
It works if you change the link for cdn chart.js to 

**https://cdn.jsdelivr.net/angular.chartjs/latest/angular-chart.min.js**

, which supposedly is the official current version
An yes, the error defined above still ocurring
Also could try to uppdate to latest angular ( 1.5.8 ) and Chart.js (i think is 2.3.0 but not sure)

**Comment by develmts** [comment] 2016-11-07 17:40
Sorry. checked again. Now it ads correctly. My mistake

**Comment by antoniomtz** [comment] 2016-11-13 00:04
How did you fix it?

**Comment by develmts** [comment] 2016-11-15 17:15
Simply updating this
` <script src=
  "https://cdn.rawgit.com/jtblin/angular-chart.js/chartjs-2.0/angular-chart.js"
  type="text/javascript">
</script>`
to this
`  <script src=
  "https://cdn.rawgit.com/jtblin/angular-chart.js/1.0.3/angular-chart.js"
  type="text/javascript">
</script>`

**Comment by mg1075** [comment] 2016-11-21 18:26
Would be great to see a fix for this issue.
`chart.update()` should definitely be called in this scenario rather than destroying and re-creating the chart.

**Comment by develmts** [comment] 2016-11-22 01:59
Angular-chart it's supposed to no use chart-updates, at least for the latest versions. Simply changing the value should make internal watchers to react ( as far as i know)

**Comment by prashasti4** [comment] 2017-01-25 08:26
I want to update chart data on button click, and the buttons are outside the div that contains chart canvas html, in this case chart not getting updated where as if I place the buttons inside parent div of chart canvas, chart does get updated, 
But becuase of my page design I can't move the buttons inside the chart parent div., How can I update chart in this case?

**Comment by nodox** [comment] 2017-03-25 00:14
Still looking for a solution to this issue. I'm updating my chart data using a websocket. The data is saved but I need to resize the window in order to get an updated chart. There is not automatic update on data change.

**Comment by jtblin** [comment] 2017-03-26 01:27
@nodox the chart updates automatically when the data change. It's basically the main purpose of this library... You can see the examples on http://jtblin.github.io/angular-chart.js/ e.g. the tick chart at the top or the [reactive example](http://jtblin.github.io/angular-chart.js/#reactive)

**Comment by jtblin** [comment] 2017-03-26 01:29
@ivanicharts the library calls `update` as much as possible but it used to not work with labels, etc. so it destroys and re-create the chart in case this kind of options change. If that has changed, happy to change that.

**Comment by nodox** [comment] 2017-03-27 15:37
@jtblin [Heres my logic](https://github.com/nodox/alexa_dispense/blob/master/src/app/dashboard/dashboard.controller.js)

I have a socket listening for updates. When the update is registered I try to update the barData object but on the front-end the change is not seen until I hover or resize the window.

**Comment by jtblin** [comment] 2017-04-28 10:33
Sorry to answer so late, you'd need to log your data to see what you get exactly: is that defined, a number, etc.? Replace you `socket.socket.on` by a `setTimeout` and I'm sure you'll see it works.

**Closed by jtblin** 2017-04-28 10:33 UTC

**Comment by zbence** [comment] 2018-04-26 07:42
I think I have the same issue. I'm updating the chart data with incoming socket.io data and my chart is not updating. Can you elaborate on this setTimeout a little bit more? 

And I also noticed this canChartUpdate method a little bit flaky see example bellow:
`canUpdateChart([1,2,3,4],[1,2,3]) -> returns false
`

Is this by design?

**Comment by zbence** [comment] 2018-04-26 16:48
Okay I got it resolved by calling $scope.$apply() inside the  io.socket.on callback body.
