### ISSUE TITLE
Legends rendered in different ways

### ISSUE THREAD

**Issue by pietro-fragnito** [jtblin/angular-chart.js#366] opened 2016-04-21 13:59 UTC
Hi at all,

I'm trying to use this library in my web app. I have problem with the rendering of the Legends about the first Line Chart of the example.

In more details I notice that:
- if I run the example myself the text _"Series"_ in wrapped in a **<span>** element (see the first figure) and putted after another **<span>** element

<img width="1274" alt="screenshot 2016-04-21 15 44 00" src="https://cloud.githubusercontent.com/assets/7511015/14711245/e474418e-07d8-11e6-895e-3adf21c93562.png">

- Instead, if I look the code of the example of the official page, the text _"Series"_ is not wrapped in the **<span>** element

<img width="1233" alt="screenshot 2016-04-21 16 00 40" src="https://cloud.githubusercontent.com/assets/7511015/14711642/72846124-07da-11e6-846d-ec9dcd463802.png">

The effect is that in my simulation the text "Series" is placed on the Legend Icon.

**Comment by rscottfree** [comment] 2016-04-21 16:41
I'm having the same issue. I think this is caused by the color swatch being absolutely positioned.

**Comment by jtblin** [comment] 2016-04-21 21:20
Have you included the css?

**Comment by davidfhaines** [comment] 2016-04-22 12:10
Same issue here.

**Comment by davidfhaines** [comment] 2016-04-22 14:43
Fixed via the following css change.

Replace
```
.chart-legend li span,
.bar-legend li span,
.line-legend li span,
.pie-legend li span,
.radar-legend li span,
.polararea-legend li span,
.doughnut-legend li span {
  display: block;
  position: absolute;
  left: 0;
  top: 0;
  width: 20px;
  height: 20px;
  border-radius: 5px;
}
```

With
```
  .chart-legend-icon,
  .bar-legend-icon,
  .line-legend-icon,
  .pie-legend-icon,
  .radar-legend-icon,
  .polararea-legend-icon,
  .doughnut-legend-icon {
    display: block;
    position: absolute;
    left: 0;
    top: 0;
    width: 20px;
    height: 20px;
    border-radius: 5px;
  }
```

**Comment by jtblin** [comment] 2016-04-23 05:24
Yes it looks like Chart.js changed the markup in `1.1.1` creating this issue.

**Closed** 2016-04-23 05:40 UTC
