### ISSUE TITLE
Bug with labels on chart doughnut

### ISSUE THREAD

**Issue by Darex1991** [jtblin/angular-chart.js#506] opened 2016-09-20 11:25 UTC
Hi Guys,
I found a bug with displaying labels on hover chart doughnut.
Branch #chartjs-2.0

![screen shot 2016-09-20 at 13 22 50](https://cloud.githubusercontent.com/assets/5881611/18668398/6f53556e-7f35-11e6-831c-b7ee912eda84.png)

When you will do it, the chart will be broken and you'll not see any hover title and chart.
I found commit bug:
[Link](https://github.com/jtblin/angular-chart.js/commit/d58886f3f44a1b9282cb0f06530fc0d4f48b82fc
)
I just what to inform you ;) Maybe in the future I'll fix it ;)

My new dependencies:
"chart": "Chart.js#v2.0.0",
"angular-chart": "git://github.com/Darex1991/angular-chart.js#chartjs-3.0",

**Comment by pietrofxq** [comment] 2016-09-22 16:54
I've updated my `angular-chart.js` to latest version and `Chart.js` to use version 2.0 as well and I'm having the same issue. I can see the chart being rendered but tooltips aren't working. I get two error messages:

```
Uncaught TypeError: Cannot read property 'length' of undefined    Chart.js:7020
Uncaught TypeError: Cannot read property 'options' of undefined  Chart.js:6967
```

**Comment by Darex1991** [comment] 2016-09-22 17:33
@pietrofxq this is what I have seen. If you want, use my last working version:
https://github.com/Darex1991/angular-chart.js/tree/chartjs-3.0

**Comment by jtblin** [comment] 2016-09-24 03:52
@Darex1991 the branch chartjs-2.0 is outdated and has been merged into master a long time ago. The fork that you are pointing to is considerably behind as well.

@pietrofxq do you have a repro case? The error that you quoted is in Chart.js and the tooltips render fine in the demo: http://jtblin.github.io/angular-chart.js/

It'd be hard to help without a repro case.

**Comment by jtblin** [comment] 2016-09-24 03:52
Closing as using an outdated branch.

**Closed by jtblin** 2016-09-24 03:52 UTC

**Comment by zygmcc** [comment] 2016-10-07 03:20
@Darex1991 yestoday I meet the same problem.After that , I update chart.js to 2.3.0 and angular-chart.js to newest version.solved
It may caused by outdated version of chart.js , DO NOT use version 2.0.X

**Comment by zygmcc** [comment] 2016-10-07 03:20
@pietrofxq update your chart.js to 2.3.0

**Comment by Darex1991** [comment] 2016-10-07 06:43
@zygmcc ooo. Good tip ;) Tnx
