### ISSUE TITLE
angular-charts not working with requirejs

### ISSUE THREAD

**Issue by vaneshmali** [jtblin/angular-chart.js#149] opened 2015-07-13 10:29 UTC
Trying to implement lazy load using requirejs. 
Everything is fine when I am not using charts. 
But when I want to use charts(angular charts), not going to sucseed! Using chart.js with angular-chart.

**Comment by jtblin** [comment] 2015-07-19 08:25
Looks like a duplicate of #147? Otherwise you should try to reformulate your problem and include repro case.

**Closed by jtblin** 2015-07-19 08:25 UTC
