### ISSUE TITLE
Hovering over line chart shows old chart data

### ISSUE THREAD

**Issue by martellaj** [jtblin/angular-chart.js#187] opened 2015-08-25 16:35 UTC
This is my scenario (using a line chart):

1. Make HTTP request to get chart data from API.
2. Add chart data to chart by assigning to a bound variable called ```chartData```.
3. User clicks a button to fetch different data, so another HTTP request is made to get new data.
4. I clear the ```chartData``` array and then add the new data.

**Expected outcome:** Chart no longer has any trace of original data, but instead shows new data and user can interact with it without issues.

**Actual outcome**: Chart shows new data, but if user hovers over the chart, it'll flicker back and forth between original and new data.

![olddata](https://cloud.githubusercontent.com/assets/1019478/9472840/766a4942-4b0c-11e5-96a9-cd6cf476fbc4.gif)

**Comment by jtblin** [comment] 2015-08-26 10:13
How do you clear the data? Passing an empty array does not clear the data, it's a chart.js issue. 
Otherwise can you post a repro case, see jsbin template in readme? It may be an issue with chart.js itself btw.

**Comment by martellaj** [comment] 2015-08-26 15:06
So it looks like it's not a Chart.js "issue", but you just have to clear data using .clear() or .destroy(). Do you have a suggestion on how to do this with the Angular directive? According to README, this should be handled automatically. I'll work on setting up a repo for you.

**Comment by jbmartinez** [comment] 2015-08-26 18:12
I have the same problem, I need to draw different data sets in the same chart and the old data keeps keeps showing. Is there a way to call .clear or .destroy on the chart?

**Comment by jbmartinez** [comment] 2015-08-26 18:51
Found a way:
```javascript
$scope.$on('create', function (event, chart) {
  ctrl.chart = chart; // ctrl is a controller reference
});
```
Then I could use `ctrl.chart.destroy()`. Surprisingly, that didn't solve the problem. I had to disable the tooltips as workaround. I would like to enable the tooltips, though.

**Comment by andre-gois** [comment] 2015-09-15 16:16
any news regarding this?

**Comment by pedrocatre** [comment] 2015-09-15 18:30
I was having the same issue. At first I tried to reproduce it using the jsbin template but there everything I tried worked. So I tried changing the values in my app the same way I was doing in the example and it also worked (basically onClick changed the values in the chart).

In the end what fixed for me was this:

In my app when a date range filter value changed I would set the values for labels and data in a service like this:

```
vm.labels = newLabels;
vm.data = newData;
````

when I changed it to this the bug stopped appearing:

```
$timeout(function() {
    vm.labels = newLabels;
    vm.data = newData;
});
```

Hope this helps others.

**Comment by TomDush** [comment] 2015-09-18 14:44
@pedrocatre , that works, thanks for the workaround!

**Comment by yaojingguo** [comment] 2015-10-04 08:36
Pie chart has the same problem. And the workaround does not work for me.

**Comment by snielson-dyn** [comment] 2015-10-08 22:55
The workaround did not work for me when I have multiple instances of charts being displayed.  I read through some discussion on the Chart.js forum and they mention this problem occurring when there are multiple instances of the chart pointing to the same canvas.  You can read the discussion here: https://github.com/nnnick/Chart.js/issues/920

I looked through the angular-charts source code and I see a number of places where the chart is being destroyed and recreated in other spots and some of them involving timeouts when the element is hidden.  I'm wondering if there is a loose reference somewhere that is being retained in a closure that is causing this behavior when a hover event is occurring.  I have to get back to my work items but I hope this initial investigation can lead to some solutions.

**Comment by yayiekim** [comment] 2015-10-31 18:37
The work around does not work for Line chart. some data aren't destroyed

**Comment by psmarcin** [comment] 2015-12-23 12:16
I think I found workaround similar to @pedrocatre 
Here is my method:

```
    /**
	 * Set chart data
	 */
	 setChartData(data) {
		var self = this;
		self.$timeout(()=> {
			self.chartConfig.labels = null;
			self.chartConfig.data = null;
			self.chartConfig.series = null;
			self.$timeout(()=> {
				self.chartConfig.labels = data.labels;
				self.chartConfig.data = data.data;
				self.chartConfig.series = data.series;
			});
		});
	}
```

**Comment by tobiastheil** [comment] 2016-01-07 14:15
The $timeout workaround didn't work for me. However, what worked is the following code inside my chart directive:

```
var $chart;
$scope.$on("create", function (event, chart) {
  if (typeof $chart !== "undefined") {
    $chart.destroy();
  }

  $chart = chart;
});
```
There are more than one chart instances... I just destroy every instance instead of the last one.

**Comment by sandy240287** [comment] 2016-02-03 08:49
@tobiastheil Thanks it worked for me.

**Comment by kr4ng** [comment] 2016-02-03 18:24
@tobiastheil Thanks so much, sweet workaround.

**Comment by jtblin** [comment] 2016-02-03 21:53
Very smart @tobiastheil, I'll try and include that in the lib directly :+1:

**Comment by gkampjes** [comment] 2016-02-17 21:18
Bugfix is inbound, should have have a PR by the weekend.

**Comment by jtblin** [comment] 2016-02-18 07:59
:+1:

**Comment by kdomagal** [comment] 2016-02-18 11:29
+1

**Comment by netmonster01** [comment] 2016-02-19 17:38
+1

**Comment by shubhampatil17** [comment] 2016-02-21 08:00
I was facing the same issue, refreshing the page using $window.location.reload() after rendering new data stopped this flickering bug in my case. Check if it helps anyone.

**Comment by robert-king** [comment] 2016-02-23 03:00
I put my chart canvas inside a div with an ng-if="chartLoaded". That way the dom element is destroyed when i load a new chart.

**Comment by MihaiDinculescu** [comment] 2016-02-26 10:47
@tobiastheil your work around yields low quality charts for me. My investigation shows that I need to keep the last 2-3 instances, not just the last one.

I have come up with this modification:

```
// store created instances
var chartInstances = [];
$scope.$on("create", function (event, chart) {
  chartInstances.push(chart);
});
```

```
// destroy all the old instances when data changes
_.each(chartInstances, function(chart) {
    chart.destroy();
});
chartInstances = [];
```

**Comment by micheledallatorre** [comment] 2016-03-01 15:25
Same problem here.
The issue happens both on LineCharts and DoughnutCharts.

I am using something very similar to this example https://ga-dev-tools.appspot.com/embed-api/ to display Google Analytics data using ChartJs charts. 

I added also a datepicker http://www.daterangepicker.com/ and whenever I change the daterange, I render the charts again.

Basically, what is done in the example above by Google is:

```
  /**
   * Update the activeUsers component, the Chartjs charts, and the dashboard
   * title whenever the user changes the view.
   */
  viewSelector.on('viewChange', function(data) {
    var title = document.getElementById('view-name');
    title.innerHTML = data.property.name + ' (' + data.view.name + ')';

    // Start tracking active users for this view.
    activeUsers.set(data).execute();

    // Render all the of charts for this view.
    renderWeekOverWeekChart(data.ids);
    renderYearOverYearChart(data.ids);
    renderTopBrowsersChart(data.ids);
    renderTopCountriesChart(data.ids);
  });
```

whereas what I do is the following.
```
        $('#daterange-btn').on('apply.daterangepicker', function(ev, picker) {
            // update date range for the Google Analytics queries
            query_start_date = picker.startDate.format('YYYY-MM-DD');
            query_end_date = picker.endDate.format('YYYY-MM-DD');
            // draw the charts again with the new chosen date range
            renderCharts('ga:' + VIEW_ID);
        });
```

Charts are updated correctly with the new chosen date range, but hovering on them display (sometimes) old data.

I tried some of the proposed solutions above, but with no luck so far... :(

**Comment by jtblin** [comment] 2016-03-12 04:30
I've now pushed a fix to always destroy the previous chart if it exists before creating a new one so it should solve this problem.

**Closed by jtblin** 2016-03-12 04:30 UTC
Labels: enhancement, repro needed, workaround

**Comment by Stefvg** [comment] 2016-03-12 19:32
It didn't solve it for me, my chart is still buggy like in the post.

**Comment by jtblin** [comment] 2016-03-12 20:55
Ah, did you use the latest from master? I haven't pushed a new version yet. 
Do you have a jsbin template where I can see the issue. Saying it doesn't help is not supra helpful without more information. The problem with having multiple charts is clearly fixed now as I always call `chart.destroy()` before creating a chart, and it is the correct fix as per https://github.com/nnnick/Chart.js/issues/920#issuecomment-167166724.

**Comment by Stefvg** [comment] 2016-03-13 10:32
Hi, yeah I even copy + pasted the code from the latest commit so I was sure that I had the last version. 
I don't have a jsbin template I think. An example of the issue is on this page: https://svg-apache.iminds-security.be/dashboard.html?app=Sample%20Filled%20Application -> select the Meter page in the top and play with the slider, you will see that the data gets updated, but if you hover over the line charts, it is buggy like in the starting post. I don't know what you have to get from me to solve this or what I have to do?

**Comment by jtblin** [comment] 2016-03-13 20:22
Well you're using the [minified file](https://svg-apache.iminds-security.be/bower_components/angular-chart.js/dist/angular-chart.min.js) on this site, that hasn't been generated with the fix so your site is **not** using the latest version right now. 

I've pushed the new version now, make sure you use `0.9.0` and let me know if that doesn't solve the problem.

**Comment by Stefvg** [comment] 2016-03-13 20:30
Hi,

It did fix the problem, thank you for the quick fix!

**Comment by jtblin** [comment] 2016-03-13 20:32
Glad to hear that! :)

**Comment by johnedvard** [comment] 2016-03-14 08:39
The update seems to work for me as well! Thank you

**Comment by micheledallatorre** [comment] 2016-03-14 08:49
Is this one the latest updated version?
https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js
(source: https://cdnjs.com/#q=chart.js)

Thanks!

**Comment by jtblin** [comment] 2016-03-14 09:16
@micheledallatorre the link you've put is for the latest stable `chart.js`. 

The latest `angilar-chart.js` which is the wrapper for `chart.js` would be //cdn.jsdelivr.net/angular.chartjs/latest/angular-chart.min.js and //cdn.jsdelivr.net/angular.chartjs/latest/angular-chart.css.

But you should install via `npm` as it will install all the dependencies for you `npm install --save angular-chart.js`.

**Comment by micheledallatorre** [comment] 2016-03-14 09:20
@jtblin Yeah, my question is the following.
Is the link to the latest stable `chart.js` posted by me above referring to the version with the fix in this thread?

Thanks.

**Comment by jtblin** [comment] 2016-03-14 09:40
Yes it is.

**Comment by micheledallatorre** [comment] 2016-03-14 13:30
@jtblin: just tried it out.

Actually decommenting my piece of code above (See UPDATE2 https://github.com/jtblin/angular-chart.js/issues/187#issuecomment-190769767), hence only loading https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js, causes the issue to appear again.

**Comment by jtblin** [comment] 2016-03-14 19:54
Mate, your example code has nothing to do with this library, it's a mix of `jQuery` and calls to a `renderChart` function. I'm not sure how you hope I can help you with that but I'm having a hard time understanding anything about you issue and how this is related to this lib. If you think the issue is with this library then please post a [jsbin](http://jsbin.com/dufibi/3/edit?html,js,output) repro case, otherwise I'd suggest you ask your question on http://stackoverflow.com/.

**Comment by micheledallatorre** [comment] 2016-03-15 08:46
Thanks @jtblin.
I created this https://jsfiddle.net/mdt86/pav5y8h1/6/ where your fix is working (i.e. updating the chart with new data, does not cause any issue hovering on the chart).

It must be some conflict in my full code, I will dig into it, thank you very much again!

**Comment by jtblin** [comment] 2016-03-15 10:03
@micheledallatorre you are not even using my library! You are using raw Chart.js: https://github.com/nnnick/Chart.js...

**Comment by micheledallatorre** [comment] 2016-03-15 10:16
Ehrrr... I think I got confused!
Searching for my problem I ended up fixing it following this discussion, but did not notice it was referring to an AngularJS version/improvement of raw Chart.js! :|

Thanks and sorry again for the misunderstanding! :)

**Comment by jazoom** [comment] 2016-11-25 08:52
I'm seeing this issue now with 2.4.0

**Comment by wangzhen10** [comment] 2017-05-04 04:16
I had the same problem. I fix this problem by deleting the div and rebuilding another div.

**Comment by anantgulia** [comment] 2017-05-19 17:43
First of all I'm using chart.js with vue 2 and the best and easiest solution i found is same as @wangzhen10 mentioned removing the element from the dom and appending it again....

**Comment by acidjazz** [comment] 2017-06-23 20:17
@anantgulia May I ask how you went about doing this in Vue?

**Comment by keisaac** [comment] 2017-07-05 06:02
I did also what @wangzhen10 mention, it works completely fine.

**Comment by gangxing** [comment] 2017-07-08 18:57
@wangzhen10 when the dataset changes,  I dynamically generate <canvas> and append it to div. yes, it WORKS for me ,thanks so much.

**Comment by gangxing** [comment] 2017-07-08 18:59
@wangzhen10 when the dataset changes, I dynamically generate `canvas` and append it to div. yes, it WORKS for me ,thanks so much.

**Comment by cinqs** [comment] 2017-08-29 09:29
Hi, just for your infos
Version: 2.6.0-non-minimized-java-webjars
Creating the chart as follows:

```javascript
var drawChart = function(labels, data, type) {
		type = type || 'bar';
		
		
		
		var ctx = document.getElementById('resultChart').getContext('2d');
		var chart = new Chart(ctx, {
			type: type,
			data: {
				labels: labels,
				datasets: [{
					label: "result of test",
					data: data
				}]
			},
			options: {
				scales: {
		            yAxes: [{
		                ticks: {
		                    beginAtZero:true
		                }
		            }]
		        }
			}
		})
	}
```
if re-invoke this method `drawChart` with a new dataset, the issues of the PO will be happening again.

But this works. (thanks @tobiastheil  )


```javascipt

var chart;

var drawChart = function(labels, data, type) {
		type = type || 'bar';
		
		if(typeof chart !== "undefined") {
			chart.destroy();
		}
		
		var ctx = document.getElementById('resultChart').getContext('2d');
		chart = new Chart(ctx, {
			type: type,
			data: {
				labels: labels,
				datasets: [{
					label: "result of test",
					data: data
				}]
			},
			options: {
				scales: {
		            yAxes: [{
		                ticks: {
		                    beginAtZero:true
		                }
		            }]
		        }
			}
		})
	}
```

**Comment by diogosanto** [comment] 2017-10-30 15:33
Hi all,
Not sure if might help somebody or not, but I was going through the same just today. The comment to "delete old data" got me thinking that maybe pushing the the data to the used array might confuse it.

So, when I removed the loop from pushing to the chart label and data array, set it to push to temporary variables and then set the chart arrays to equal the final result, it got fixed for me.

Because I know I am not the best at explaining, I will post the code below:

__Problematic Example:__
```
servers.forEach(function (value, key) {
   AjaxController.data.dataServerWebsites.labels.push(value.name);
   AjaxController.data.dataServerWebsites.websites.push(value.total);
});
ChartController.functions.serverWebsites();
```
__Fixed Example:__
```
servers.forEach(function (value, key) {
   tempLabels.push(value.name);
   tempData.push(value.total);
});

AjaxController.data.dataServerWebsites.labels = tempLabels;
AjaxController.data.dataServerWebsites.websites = tempData;
ChartController.functions.serverWebsites();
```

Hope it helps! :)

**Comment by strix25** [comment] 2017-11-03 19:51
I still have this problem with version: https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.bundle.js

code: 
`function charterino(){

let myChart = document.getElementById('myChart').getContext('2d');

    // Global Options
    Chart.defaults.global.defaultFontFamily = 'Lato';
    Chart.defaults.global.defaultFontSize = 18;
    Chart.defaults.global.defaultFontColor = '#FFF';

    let massPopChart = new Chart(myChart, {
      type:'bar', // bar, horizontalBar, pie, line, doughnut, radar, polarArea
      data:{
        labels:['January', 'February', 'March', 'April', 'May', 'June'],
        datasets:[{
          label:'Hours',
          data:[
            jan,
            feb,
            mar,
            apr,
            may,
            jun
          ],
          //backgroundColor:'green',
          backgroundColor:[
            'rgba(255, 99, 132, 0.6)',
            'rgba(54, 162, 235, 0.6)',
            'rgba(255, 206, 86, 0.6)',
            'rgba(75, 192, 192, 0.6)',
            'rgba(153, 102, 255, 0.6)',
            'rgba(255, 159, 64, 0.6)',
            'rgba(255, 99, 132, 0.6)'
          ],
          borderWidth:1,
        //borderColor:'#777',
          hoverBorderWidth:3,
          hoverBorderColor:'#000'
        }]
      },
      options:{
        title:{
          display:true,
          text:`Hours worked per month for: ${employeeName}`,
          fontSize:25
        },
        legend:{
          display:true,
          position:'right',
          labels:{
            fontColor:'#000'
          }
        },
        layout:{
          padding:{
            left:50,
            right:0,
            bottom:0,
            top:0
          }
        },
        tooltips:{
          enabled:false
        },
        scales: {
            
            yAxes: [{
                ticks: {
                    suggestedMin: 140
                    
                }
            }]
        }
      }
    });

  };`

**Comment by jayanthjoseph** [comment] 2017-12-07 07:58
This worked for me..
Before calling create chart call destroy()

  if(this.myChart){
       this.myChart.destroy();
     }
createmyChart()

**Comment by TamkeenLMS** [comment] 2018-01-13 08:57
I am still facing the same issue here! Every time the data is updated it's added to the existing chart not refreshed! 

![capture](https://user-images.githubusercontent.com/13228056/34904536-82a8bfce-f850-11e7-929b-fb7f7700bf4d.PNG)

**Comment by strix25** [comment] 2018-01-13 09:36
@TamkeenLMS  take a look at  this example https://github.com/strix25/attSys/tree/master/js maybe it helps you

**Comment by TamkeenLMS** [comment] 2018-01-13 09:43
@strix25 I don't see any angular js code. The problem isn't with chart.js itself, it's waith angular-chart.js. The library simply should redraw the chart after data change, I don't understand how this is an issue?! it's just makes sense!

**Comment by FlightToFreedom** [comment] 2018-02-08 11:24
Have you tried:
http://www.chartjs.org/docs/latest/developers/updates.html

**Comment by crosshat** [comment] 2018-02-13 14:38
`drawChart() {
    if (this.chart) {
      this.chart.destroy();
    }
    const cntx = this.elementRef.nativeElement.querySelector('canvas');
    this.chart = new Chart(cntx, {
      type: 'line',
      data: {
        labels: this.yearArray,
        datasets: [
          {
          label: 'No. of Death',
          data: this.deathArray,
          borderColor: 'rgb(153, 204, 255)',
          fillColor: 'red'
          }
        ]
      },
      options: {
        maintainAspectRatio: false,
        legend: {
            display: true
        }
      }
    });
  }`

**Comment by crosshat** [comment] 2018-02-13 14:38
`
drawChart() {
    if (this.chart) {
      this.chart.destroy();
    }
    const cntx = this.elementRef.nativeElement.querySelector('canvas');
    this.chart = new Chart(cntx, {
      type: 'line',
      data: {
        labels: this.yearArray,
        datasets: [
          {
          label: 'No. of Death',
          data: this.deathArray,
          borderColor: 'rgb(153, 204, 255)',
          fillColor: 'red'
          }
        ]
      },
      options: {
        maintainAspectRatio: false,
        legend: {
            display: true
        }
      }
    });
  }
`

**Comment by crosshat** [comment] 2018-02-13 14:39
>   drawChart() {
    if (this.chart) {
      this.chart.destroy();
    }
    const cntx = this.elementRef.nativeElement.querySelector('canvas');
    this.chart = new Chart(cntx, {
      type: 'line',
      data: {
        labels: this.yearArray,
        datasets: [
          {
          label: 'No. of Death',
          data: this.deathArray,
          borderColor: 'rgb(153, 204, 255)',
          fillColor: 'red'
          }
        ]
      },
      options: {
        maintainAspectRatio: false,
        legend: {
            display: true
        }
      }
    });
  }

**Comment by SensationSama** [comment] 2018-06-06 18:46
Following @storesbuzz solution

Here's a pure javascript approach where the id is preserved on the canvas element.
`
let container = document.getElementById('canvasContainer');
let oldInstance = document.getElementById('myGraph');
container.removeChild(oldInstance);
let newInstance = document.createElement("canvas");
newInstance.setAttribute("id", "myGraph");
container.appendChild(newInstance);
`

**Comment by RayOjuka** [comment] 2019-02-27 13:52
> > Easy fix for angular 5!!!
> > chart: any;
> 
> > drawChart() {
> > if (this.chart) {
> > this.chart.destroy();
> > }
> > const cntx = this.elementRef.nativeElement.querySelector('canvas');
> > this.chart = new Chart(cntx, {
> > type: 'line',
> > data: {
> > labels: this.yearArray,
> > datasets: [
> > {
> > label: 'No. of Death',
> > data: this.deathArray,
> > borderColor: 'rgb(153, 204, 255)',
> > fillColor: 'red'
> > }
> > ]
> > },
> > options: {
> > maintainAspectRatio: false,
> > legend: {
> > display: true
> > }
> > }
> > });
> > }

@crosshat I did this and am getting the following error.
property 'destroy' does not exist on type any.
This on angular 6

**Comment by fazal-michelangelo** [comment] 2019-08-06 14:11
> The $timeout workaround didn't work for me. However, what worked is the following code inside my chart directive:
> 
> ```
> var $chart;
> $scope.$on("create", function (event, chart) {
>   if (typeof $chart !== "undefined") {
>     $chart.destroy();
>   }
> 
>   $chart = chart;
> });
> ```
> 
> There are more than one chart instances... I just destroy every instance except the last one.

Can you please provide related angularjs code

**Comment by ArntB** [comment] 2019-11-04 21:39
I just encountered the same issue. Thanks for all the tips here. It helped but none of these completely eliminated the problem.

In the end I figured out that the cause of the problem was that the destroy call and new call sometimes happened in a different order. I moved the destroy logic to the same function as where I updated the chart and It worked. Some how when I had the destroy in a function calling my updateChart function button clicks interfered and messed up clear and new.
Did this I in Angular 7.

**Comment by ZTF666** [comment] 2020-04-02 11:41
> 
> 
> @TamkeenLMS take a look at this example https://github.com/strix25/attSys/tree/master/js maybe it helps you

This is one is a life saver !! thanks mate <3

**Comment by rohitksingh** [comment] 2020-04-18 03:14
I faced the same problem. To fix this I made my chart variable as global. Then I added a check condition if the chart has some value in it. If so then destroy the instance. 

## The code

  ```
let mychart

  function somefunc(){
       if(myChart){
            myChart.destroy();
        }

       myChart = new Chart(ctx, {
           type: 'bar',
           data: {
               labels : ["test_month"]
           },
       });
  }
```

**Comment by Ntsou2020** [comment] 2020-09-18 13:54
I use nodeJS, and ChartJS 2.8

and I have the same problem when I hover over the new map, if I happen to pass over specific locations corresponding to points displayed on the old map, the hover/tag is still triggered and the old map is suddenly visible. It remains visible as long as my mouse is there and disappears when I move away from that point. I don't want the old map to be displayed. I want to delete it completely.

When I use functions like mychart.destroy() , mychart.clear() , mychart.update() I get errors like "Cannot read property 'destroy' of undefined".

I have already run the npm command install chart.js --save

Are there things I need to import?

Here are my lines of code

HTML

`<div class="col-4 chart">
            <canvas id="myChart1" width="500" height="500"></canvas>               
  </div>`

JavaScript

`var graph = document.getElementById('RegChart');
function onChangeGraph() {
 var Reggraph = graph.value

if (Reggraph === 'AlaotraMangoro') {
let labels1 = ['[Moins de 1 ans[', '[1 à 5[', '[5 à 10[','[10 à 15[', '[15 à 20[', '[20 à 30[', '[30 à 40[', '[40 à 50[', '[50 à 60[', '[Plus de 60['];
let data1 = [59.0, 33.0, 29.3, 31.1, 16.1, 23.7, 25.2, 39.7, 36.5, 36.0];
let colors1 = ['#EADEDC', '#F54036', '#0AA0EE', '#E1EE0A', '#011C0A', '#6F7272', '#5ceca2', ' #2c0ec5 ', '#eca50e', '#0ee2ec'];

var myChart1 = document.getElementById('myChart1').getContext('2d');
var chart1 = new Chart(myChart1, {
type: 'doughnut',

// The data for our dataset
data: {
    labels: labels1,
    datasets: [{
        
        backgroundColor: colors1,
        data: data1,
    }]
},

// Configuration options go here
options: {
    title: { 
        text: "Taux de consultation ",
        display: true
    },
        legend: {
        display: true,
        position: "right"
    }
},
});
}
if (Reggraph === 'AmoroniMania') {
myChart1.destroy()
// CHART 1
 let labels1 = ['[Moins de 1 ans[', '[1 à 5[', '[5 à 10[','[10 à 15[', '[15 à 20[', '[20 à 30[', '[30 à 40[', '[40 à 50[', '[50 à 60[', '[Plus de 60['];
 let data1 = [49.0, 39.7, 25.4, 16.0, 40.3, 29.1, 7.6, 37.5, 29.0, 21.9];
 let colors1 = ['#EADEDC', '#F54036', '#0AA0EE', '#E1EE0A', '#011C0A', '#6F7272', '#5ceca2', ' #2c0ec5 ', '#eca50e', '#0ee2ec'];
var myChart1 = document.getElementById('myChart1').getContext('2d');
var myChart1 = new Chart(myChart1, {
 // The type of chart we want to create
 type: 'doughnut',

 // The data for our dataset
 data: {
     labels: labels1,
     datasets: [{
         
         backgroundColor: colors1,
        // borderColor: 'rgb(255, 99, 132)',
         data: data1,
     }]
 },

 // Configuration options go here
 options: {
     title: { 
         text: "Taux de consultation groupe",
         display: true
     }
 }
});
}
}
graph.addEventListener('change', onChangeGraph);
onChangeGraph(); `

**Comment by Rainangramacho** [comment] 2021-01-28 13:21
> I faced the same problem. To fix this I made my chart variable as global. Then I added a check condition if the chart has some value in it. If so then destroy the instance.
> 
> ## The code
> ```
> let mychart
> 
> function somefunc(){
>      if(myChart){
>           myChart.destroy();
>       }
> 
>      myChart = new Chart(ctx, {
>          type: 'bar',
>          data: {
>              labels : ["test_month"]
>          },
>      });
> }
> ```

Thanks @rohitksingh!! Your solution worked for me!

**Comment by hayat12** [comment] 2021-02-10 13:55
keep your chart as child component. every time when you change the data. refresh the child component for example  
`
<app-my-chart id="chartId" options="chartOption" data="chartData"></app-my-chart>
`
your child component as follow
`@Component({
 selector: 'app-my-chart',
  template:'
<div id="mychart">
  <canvas [id]="chartId"></canvas>
</div>
'
  styles: ['']
})

export class MyChartComponent implements AfterViewInit {
@Input() id:string;
 type:string;
@Input() options;
@Input() data;

  ngAfterViewInit(){
    this.initChart();
  }
  initChart(){
    const canvas = <HTMLCanvasElement>document.getElementById(this.chartId);
    const ctx = canvas.getContext('2d');
    const mychart = new Chart(ctx, {
      type: this.type,
      data:this.data,
      options:this.options
    });
}
  }
`

**Comment by leilagattas** [comment] 2021-03-26 17:08
Using ANGULAR, I solved it calling this function before the creation of the graph

 destroyGraph(grafico: Chart | undefined) {
    if (typeof (grafico) !== "undefined") {
      grafico.destroy();
    }
  }

**Comment by finserveInfotech** [comment] 2021-09-15 09:34
thank you so much .....problem solved
