### ISSUE TITLE
Small Installation doc mistake

### ISSUE THREAD

**Issue by lenanex** [jtblin/angular-chart.js#433] opened 2016-07-15 07:21 UTC
### Overview

In the installation manual, one mistake : 

<script src="node_modules/angular-chart.js/dist/angular-chart.min.js"></script> -> appearing twice, should be removed as the order is useful.
<script src="node_modules/chart.js/Chart.min.js"></script>  -> 
<script src="node_modules/angular-chart.js/dist/angular-chart.min.js"></script> 

Nothing major, but could help other to install it.

Thanks,
Nanex

**Comment by jtblin** [comment] 2016-07-19 11:28
Duplicate of #428

**Closed by jtblin** 2016-07-19 11:28 UTC
Labels: duplicate
