### ISSUE TITLE
Package npm:chart.js not found

### ISSUE THREAD

**Issue by artuska** [jtblin/angular-chart.js#467] opened 2016-08-17 10:36 UTC
### Overview

Installing of the `angular-chart.js` is broken.

### Step to reproduce

Just try to run `bower install angular-chart.js` and see the erros below:

```
}, {
  "code": "ENOTFOUND",
  "data": {
    "endpoint": {
      "name": "chart.js",
      "source": "npm:chart.js",
      "target": "2.x"
    }
  },
  "id": "ENOTFOUND",
  "level": "error",
  "message": "Package npm:chart.js not found",
  "stacktrace": "Error: Package npm:chart.js not found\n    at createError (/usr/local/lib/node_modules/bower/lib/util/createError.js:4:15)\n    at /usr/local/lib/node_modules/bower/lib/core/resolverFactory.js:206:23\n    at _fulfilled (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:834:54)\n    at self.promiseDispatch.done (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:863:30)\n    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:796:13)\n    at /usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:604:44\n    at runSingle (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:137:13)\n    at flush (/usr/local/lib/node_modules/bower/lib/node_modules/q/q.js:125:13)\n    at nextTickCallbackWith0Args (node.js:452:9)\n    at process._tickCallback (node.js:381:13)"
}]
```

**Comment by artuska** [comment] 2016-08-17 10:50
Well, this happens because of `bower install`. If I use `package.json` and `npm install` or `npm install angular-chart.js` instead of `bower.json` and `bower install` or `bower install angular-chart.js` everything is fine.

**Comment by kklein623** [comment] 2016-08-17 20:27
+1

Having the same issue. Checked it out and the bower.json looks like chart.js is pulling in the wrong string for a version, grabbing "npm:chart.js#2.x" instead of "2.x". Best fix for now would be to just revert to 1.0.0.

**Comment by jtblin** [comment] 2016-08-17 21:13
Have you followed the instructions in the readme and install the
bower-npm-resolver? Chart.js has dropped support for bower so it's the only
way to use bower now.
I'd recommend switching to npm anyway.

**Comment by TimmyParkwayd** [comment] 2016-08-18 08:09
I have the same issue, and I followed the instructions in the readme. It seems that angular-chart.js do not find chart.js . I think this is the same problem as https://github.com/jtblin/angular-chart.js/issues/466
Did somebody find a way to use this with bower ? I can't use anything else ...

**Comment by jtblin** [comment] 2016-08-18 08:49
@TimmyParkwayd out of curiosity, why can't you use npm instead of bower?

**Comment by TimmyParkwayd** [comment] 2016-08-18 08:54
Hello @jtblin . 
Because my project i am using automatic injection of dependencies with bower (I have a lot of dependencies)  and using npm would break the architecture of the project ... :/

**Comment by jtblin** [comment] 2016-08-18 08:59
Maybe you should use something like webpack to combine all dependencies into a bundle and use this bundle but ¯\_(ツ)_/¯.

**Comment by TimmyParkwayd** [comment] 2016-08-18 10:06
There no easier way to do it ? :( 
I think a lot of people would like to use it with bower and the installation doesn't seems to work as it is indicate in the readme .

**Comment by frlinw** [comment] 2016-08-18 10:51
@TimmyParkwayd if you wanna know more about this npm-only choice, check here https://github.com/chartjs/Chart.js/issues/3033
Anyway, you are a human being, you'll find a solution, it's our nature. good luck!

**Comment by qgliu** [comment] 2016-08-18 17:40
I'm running into the same problem. I'm using gulp and bower-files to merge all the js supporting files. Although using the npm:chart can install chart with bower, it still breaks my merged file. It keeps complaining something like "Module 'chart.js' is not available". Wonder if there is a solution to that.

**Comment by jtblin** [comment] 2016-08-18 21:44
@TimmyParkwayd It doesn't work anymore because Chart.js removed support for bower. We'll give it a try to the 'overrides` option but if that doesn't work then we'll have to follow Chart.js and remove bower support entirely as well.

**Comment by jtblin** [comment] 2016-08-19 08:50
Closing as duplicate of #466

**Closed by jtblin** 2016-08-19 08:50 UTC

**Comment by atomicleopard** [comment] 2016-09-12 04:53
I've had this problem as well, and using the build tooling (grunt, grunt-bower-task) for this project i've been unable to resolve it using any combination of the available options. Is it possible that angular-chart.js could refer to chartjs in it's bower.json by github repo? That way bower works without requiring an npm dependency as well.

**Comment by Wolfhergang** [comment] 2016-09-22 16:23
Hi there, Charts.js bower native support its back, you could update your dependency now and it should work as expected. :)
