### ISSUE TITLE
Wrong colors on bar chart

### ISSUE THREAD

**Issue by jldm11** [jtblin/angular-chart.js#50] opened 2015-02-04 19:30 UTC
Comparing tooltip colors on line chart and bar chart, it seems like in line chart shown colors are taken from the line and not from the fill, but in bar chart the color seems to be taken from the fill color. Also the bars doesn't highlight when the mouse is over.

**Comment by jtblin** [comment] 2015-02-07 02:32
Thanks for catching this. This comes directly from chart.js, see https://github.com/nnnick/Chart.js/blob/master/Chart.js#L2139, Chart.js use different color properties for lines and bars:

**strokeColor and fillColor**:
Chart.js use  `strokeColor` and `fillColor` for bars instead of `pointStrokeColor` and `pointColor`  like for lines. 

**highlightFill and highlightStroke**:
Chart.js use `highlightFill` and `highlightStroke` for bars instead of `pointHighlightFill` and `pointHighlightStroke` like for lines. 

So it is not only the tooltip but the also the points themselves that use different set of colours. I can't say if it's a bug or by design as changing make the bar charts look very different from today.

![image](https://cloud.githubusercontent.com/assets/1388974/6090358/0736467c-aeca-11e4-9427-846e7e293771.png)

Maybe you want to open an issue on their tracker, not sure how to fix that.

**Comment by jtblin** [comment] 2015-04-25 07:49
As issue is upstream and changing that would have quite an impact on existing charts, I'm going to close this as won't fix.

**Closed by jtblin** 2015-04-25 07:49 UTC
Labels: minor, upstream, wontfix
