### ISSUE TITLE
on chrome text is not rendering in chart labels

### ISSUE THREAD

**Issue by nicolaveritas** [jtblin/angular-chart.js#267] opened 2015-12-10 11:13 UTC
I'm working on MBP running OS X 10.11.1, the problem appears only with Chrome Browser (version 47.0.2526.80)

Here is a screenshot of what i see 

![chart](https://cloud.githubusercontent.com/assets/10831345/11713992/1b241bce-9f37-11e5-9547-4c7430687a7a.jpg)

Even at http://start-angular.github.io/sb-admin-angular/preview/#/dashboard/chart is the same
On Safari and Mozilla no problem at all

**Comment by jtblin** [comment] 2015-12-10 20:14
I use Chrome on MBP running OS X 10.11.1 as well and I don't have these issues so pretty sure the problem is on your side only.

**Comment by Bratkartoffl** [comment] 2015-12-28 13:39
I have the same issue on OSX 10.11.2. Any idea why this happens?

**Comment by sennav** [comment] 2016-01-20 15:05
Same here, Chrome  47.0.2526.111 (64-bit) Mac OS X. Safari OK.

**Comment by nicolaveritas** [comment] 2016-01-20 15:13
I have noticed just today that I have the issue just running chrome with --disable-web-security, otherwise render is ok

**Comment by sennav** [comment] 2016-01-20 18:02
I've experienced it with the dev tools open. With the dev tools closed the donut chart works ok but I the popup of the line chart still doesn't work.

**Comment by jtblin** [comment] 2016-01-29 22:54
Closing as unlikely to have anything to do with my lib. My main browser is Chrome and I don't experience this kind of issue.

**Closed by jtblin** 2016-01-29 22:54 UTC
