### ISSUE TITLE
Chart Line with only 1 data is not showing properly

### ISSUE THREAD

**Issue by PuKoren** [jtblin/angular-chart.js#32] opened 2015-01-15 12:05 UTC
The dot on the chart is not present and the label is draw on the top left corner of the chart (my label is *1/14*):
![screenshot from 2015-01-15 13 04 23](https://cloud.githubusercontent.com/assets/4202557/5756998/db90f5d2-9cb6-11e4-86a9-d8f179c16e4a.png)

My data object (1 have 3 series):

    Array: [[1], [], []]

My label object:

    Array: ["1/14"]

**Comment by jtblin** [comment] 2015-01-16 09:57
I am not sure what kind of chart you try to draw but I was able to repro with a line chart but if you add an another point, it works e.g. http://jsbin.com/mecowu/1/edit?html,js,output. This is because you need at least 2 points to draw a line.

With a bar chart, it works fine even with only one point: http://jsbin.com/meticu/1/edit?html,js,output.

**Comment by jtblin** [comment] 2015-01-16 09:59
Closing as by design (needs 2 points to draw a line. I believe this is a limitation of [Chart.js](https://github.com/nnnick/Chart.js) itself.

**Closed by jtblin** 2015-01-16 09:59 UTC
