### ISSUE TITLE
Setting global colors doesn't work

### ISSUE THREAD

**Issue by thany** [jtblin/angular-chart.js#616] opened 2017-03-17 16:26 UTC
### Overview

Setting the global chart colours in ChartJsProvider doesn't work. It just doesn't work - so there are no errors or warnings. The options appear to be accepted, somewhere, but they're completely ignored. It always uses the default chart colours.

So, something like this...
```js
module.config(["ChartJsProvider", function(ChartJsProvider) {
  ChartJsProvider.setOptions({
    colors: [ "#00988c", "#85cdde", "#bd1622", "#e74e0f" ]
  });
}]);
```
...won't work. Please note that this is exactly as in the [Getting started](https://jtblin.github.io/angular-chart.js/#getting_started) section, so I have to assume I'm not doing anything horribly wrong 🙂

However, setting default chart colours like this *will* work:
```js
Chart.defaults.global.colors = [ "#00988c", "#85cdde", "#bd1622", "#e74e0f" ];
```

- [x] Use latest version of the library
Yup, freshly installed today from bower.

- [x] Make sure you've included all the dependencies e.g Chart.js, angular, etc.
Yup, my application or any charts wouldn't work otherwise.

- [x] Include a repro case, see below.
Yup, see below indeed 🙂

### Step to reproduce

Set the chart colours in the same way as the instructions on the [Getting started](https://jtblin.github.io/angular-chart.js/#getting_started) section.

Here's a [jsbin for convenience](http://jsbin.com/qobiwazuto/edit?html,js,output), it'll demonstrate the custom colours not being used at all.

**Comment by mateutek** [comment] 2017-03-22 22:59
```javascript
ChartJsProvider.setOptions({
    global:{
        colors : ['#2196f3','#607d8b'],
        defaultFontColor: '#FFFFFF',
        defaultFontFamily: 'Roboto',
        defaultFontSize: 13
    }
});
```
Works

**Comment by thany** [comment] 2017-03-23 09:20
Ah well then maybe the Getting Started section should be updated with this :)

**Comment by jtblin** [comment] 2017-03-26 02:17
Duplicate of #512

**Closed by jtblin** 2017-03-26 02:17 UTC
